# 标签页图标
favicon:
  type: "image/x-icon"
  href: "/favicon.ico"

# canvas 动态背景
canvas_dust: true

# 默认颜色模式 dark / dark-only / light / light-only / auto
# dark 暗色模式
# light 亮色模式
# -only 锁定颜色模式
# auto 跟随系统
color: auto

# <body> 背景图片链接
background_image:
  dark: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # 暗色模式
  light: /img/bk.jpg # 亮色模式

# 导航栏
menu:
  '主 页': ""
  '关 于': about/
  # Contact: contact/
  '归 档': archives/

# 侧边栏
aside:
  in_left: false # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/4.png #图片链接，建议 1:1 比例
  logo_margin: 0 # 为 Logo 图片设置 CSS margin 属性值，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/margin
  logo_border_radius: 0 # 为 Logo 图片设置 CSS border-radius 属性值，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-radius
  dr: / # 侧边栏 Dr. 链接
  icp: # ICP 备案号，与版权声明相同，但会链接到 https://beian.miit.gov.cn/
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    # 萌:
    #   萌ICP备XXXXXXXX号: https://icp.gov.moe/?keyword=XXXXXXXX
    # copyright:
    #   CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh

# 社交链接
# 格式：链接 || 图标
# 图标支持链接与 FontAwesome
# FontAwesome 格式可用图标参考：https://fontawesome.com/icons
social:
  GitHub: https://github.com/what-is-me || fab fa-github
  E-Mail: whatisme@outlook.jp || fa fa-envelope
  BiliBili: https://space.bilibili.com/85709895 || fa-brands fa-bilibili
  # Weibo: https://weibo.com/yourname || fab fa-weibo
  # Zhihu: https://www.zhihu.com/people/yourname || fab fa-zhihu

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  excerpt: true # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  post-info: true # 文章页右上角发布/更新日期
  post-index: true # 侧边栏的目录
  # 文章末显示打赏二维码
  reward:
    # 支付宝 | Alipay: img/Alipay.png
    # 微信 | Wechat: img/WeChat.png
  # 以下两项依赖 hexo-wordcount，请参阅 README 开启
  count: true # 是否显示字数统计
  time: true # 是否显示预计阅读时长
  code_fold: 15 # 当代码小于等此行数时默认展开，设为 -1 则全部展开

# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度

# 归档页
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索
search:
  enable: true
  content: true # 若为 false，仅可搜索标题及 metadata
  preload: false # 自动加载搜索数据
  # 设为 post 时，仅可搜索 post 页面
  # 设为 page 时，仅可搜索非 post 页面
  # 设为 all 时，可搜索全部页面
  field: post
  # 设为 html 时，依据 html 文件生成
  # 设为 striptags 时，滤除 html tag
  # 设为 raw 时，依据 markdown 源文件生成
  format: striptags

# 背景音乐
bgm:
  enable: false
  autoplay: true
  loop: true
  src: /audio/bgm.mp3

# 不蒜子
# 详见 http://busuanzi.ibruce.info/
busuanzi:
  enable: true
  sitePV: true # 站点总访问量
  siteUV: true # 站点访客数
  pagePV: true # 页面访问量

# Valine
# 详见 https://valine.js.org
valine:
  enable: false
  app_id: # APP ID
  app_key: # APP KEY
  server_url: # APP DOMAIN（LeanCloud 国际版）
  avatar: 'retro' # (''/mp/identicon/monsterid/wavatar/robohash/retro/hide)
  avatar_cdn: 'https://dn-qiniu-avatar.qbox.me/avatar/' # 自定义 avatar cdn

# gitalk
# 详见 https://github.com/gitalk/gitalk
gitalk:
  enable: true
  client_id: 0a1567775fb9324a7fc6 # GitHub 应用 Client ID
  client_secret: 83480de27cdc25848e4db90f049d8446d0050b41 # GitHub 应用 Client Secret
  repo: what-is-me.github.io # 用于存放评论数据的 GitHub 仓库
  owner: what-is-me # 该 GitHub 仓库所有者
  admin: ['what-is-me'] # 具有写该 GitHub 仓库权限的用户，例如: [adminA,adminB]
  id: location.pathname # (可选) 页面的唯一标识
  labels: ['Gitalk']
  createIssueManually: true

# Waline
# 详情: https://waline.js.org/
waline:
  enable: false
  server_url: #Server_Url

#Artalk
#详见：https://artalk.js.org/
artalk:
  enable: false
  server: https://artalk.server.instance/ # 你的 Artalk 服务地址
  site_name: My Blog # 站点名称，用于区分多个站点（可选）

# 图表支持
mermaid:
  enable: true
  version: "10.5.0"

# pjax 支持
pjax:
  enable: true

# 公式前端渲染
mathjax:
  enable: true
  version: "2.6.1"

# 在 `<head>` 标签内引入 CSS 样式表
# 支持直接引入短片段，用 "{ }" 包裹（包括引号），例： - "{a {color: #2bf}}"
stylesheets:

# 在 `<body>` 尾部引入 JavaScript 脚本
# 支持直接引入短片段，用 "{ }" 包裹（包括引号），例： - "{var test='test'}"
scripts:
